<div class="landingPage">
    <div class="top">
        <div class="cleverreachLogo">
            <img src="<?= $this->getViewFileUrl('Test_CleverreachPlugin::images/cleverreach.png'); ?>" />
        </div>
        <div class="clientId">
            Client ID: <?= $block->getClientId() ?>
        </div>
    </div>
    <div class="status">
        <div>Sync Status:</div>
        <div class="statusValue">Done</div>
    </div>
    <div class="buttonDiv">
        <button class="connectButton"> Synchronize </button>
    </div>
</div>
