<div class="landingPage">
    <div class="cleverreachLogo">
        <img src="<?= $this->getViewFileUrl('Test_CleverreachPlugin::images/cleverreach.png'); ?>" />
    </div>
    <div class="content">
        <div>
            <img src="<?= $this->getViewFileUrl('Test_CleverreachPlugin::images/icon_quickstartmailing.svg');?>"
                 class="iconStartMailing" />
        </div>
        <div class="title">
            Welcome to CleverReach
        </div>
        <div class="textField">
            Connect, sync customer data and create appealing emails to showcase your products to your customers.
        </div>
        <div class="buttonDiv">
                <button class="connectButton"
                        onclick="openCleverReachPopUp('<?= $block->escapeHtml($block->getLoginPageUrl()); ?>',
                                '<?= $block->escapeHtml($block->checkLoginUrl()); ?>',
                                '<?= $block->escapeHtml($block->redirectToDashboard()); ?>')"
                > Connect </button>
        </div>
    </div>
</div>

<script>
    localStorage.removeItem('initialSyncDone');
    let checkLoginCall;
    function openCleverReachPopUp(url, checkUrl, redirectUrl) {
        window.open(url, '_blank', 'location=yes,height=570,width=900,scrollbars=yes,status=yes');
        checkLoginCall = setInterval(function() {
            checkLogin(checkUrl, redirectUrl, checkLoginCall)
        }, 1000);
    }

    function checkLogin(checkUrl, redirectUrl) {
        let xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            console.log(this.responseText);
            if(this.readyState === 4 && this.responseText === '1') {
                clearInterval(checkLoginCall);
                window.location.replace(redirectUrl);
            }
        }

        xhttp.open('GET', checkUrl);
        xhttp.send();
    }
</script>
